# Generated by Django 5.1.7 on 2025-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquet_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('descreption', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Bouquets')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
            ],
        ),
    ]
