# Generated by Django 5.1.7 on 2025-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bouquet_medicaltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='medical_test',
            field=models.ManyToManyField(to='base.medicaltest'),
        ),
    ]
