# Generated by Django 5.1.7 on 2025-05-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('natural_value', models.CharField(max_length=100)),
                ('evaluation', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicaltest')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_test', models.ManyToManyField(through='base.Analysis', to='base.medicaltest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='resultsanalysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.resultsanalysis'),
        ),
    ]
