# Generated by Django 5.1.7 on 2025-08-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_analysis_resultsanalysis_analysis_resultsanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.CharField(blank=True, default=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='file_discount',
            field=models.FileField(blank=True, null=True, upload_to='images/Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.CharField(blank=True, default=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_discount',
            field=models.CharField(blank=True, default='no discount', max_length=100, null=True),
        ),
    ]
