# Generated by Django 5.1.7 on 2025-08-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_discount_order_file_discount_order_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.BooleanField(blank=True, default=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, max_length=25, null=True),
        ),
    ]
